### ISSUE TITLE
maven 运行时报错。

### ISSUE THREAD

**Issue by se777en** [wendal/nutz-book-project#41]
`zao@zao-desktop ~/zhouqz/nutzcn $ mvn jetty:run
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Unnamed - nutzbook:nutzbook:war:2.9.3
[INFO]    task-segment: [jetty:run]
[INFO] ------------------------------------------------------------------------
[INFO] Preparing jetty:run
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 44 resources
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Unable to get dependency information: Unable to read the metadata file for artifact 'com.google.code.gson:gson:jar': Invalid JDK version in profile 'doclint-java8-disable': Unbounded range: [1.8, for project com.google.code.gson:gson
  com.google.code.gson:gson:jar:2.3

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  nutz-snapshots (http://maven.nutz.cn/nexus/content/repositories/snapshots),
  nexus-nutzcn-thirdparty (http://maven.nutz.cn/nexus/content/repositories/thirdparty),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
  nutz (http://maven.nutz.cn/nexus/content/repositories/central)

Path to dependency: 
	1) nutzbook:nutzbook:war:2.9.3
	2) cn.jpush.api:jpush-client:jar:3.2.8

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Sun Nov 27 18:58:21 CST 2016
[INFO] Final Memory: 25M/173M
[INFO] ------------------------------------------------------------------------`

**Comment by wendal** [comment]
要用JDK8运行.

**Comment by lishoujun** [comment]
maven 版本太低，请使用 maven 3+ 执行。
