### ISSUE TITLE
nutz如何获取游标里面的值？

### ISSUE THREAD

**Issue by freddy24** [wendal/nutz-book-project#47]
文档里面调用存储过程，没有游标的例子。我试了两种方法：
第一种：
Sql sql = Sqls.create("CALL ss.c_realtime(" +
                " @i_cont," +
                " @OUTo_cur_main," +
                " @OUTo_success)");
        sql.setParam("i_cont", cont);
        sql.setParam("OUTo_cur_main", OracleTypes.CURSOR);
        sql.setParam("OUTo_success", OracleTypes.VARCHAR);
        dao.execute(sql);
        Record record = sql.getOutParams();
        String success = record.getString("o_success");
        Object object = record.get("o_cur_main");
        得到的object是一个 forwardOnlyResultSet对象，转成ResultSet对象，rs.next()为false，无法获取里面的值。

第二种：
dao.run(new ConnCallback() {
            @Override
            public void invoke(Connection conn) throws Exception {
                CallableStatement cs = conn.prepareCall(sql1);
                cs.setString(1, contractNo);
                cs.registerOutParameter(2, OracleTypes.CURSOR);
                cs.registerOutParameter(3, OracleTypes.VARCHAR);
                cs.execute();
                ResultSet resultSet = null;
                resultSet = cs.getResultSet();
               ResultSet data2 = (ResultSet) cs.getObject(2);
一样的 data2.next为false ，无法获取里面的值，
请问这要怎么获取游标里面的值？求解？

**Comment by wendal** [comment]
会有多个ResultSet的, 通过cs.hasMore()判断
